components/InputField.vue
pages/login.vue

close #14 
- inputフィールド＋labelのコンポーネントを作成しました。
- font-sizeはとりあえずベタ書きしています。
- actionの類は別途要検討です。

InputFieldコンポーネントを追加

---

.prettierrc
components/PageHeader.vue
package.json

close #64 
- lintの設定を見直しました。
- eslint, stylelintをかけて問題ない状態になっています。

lintの設定を見直し

---

components/PatientGraph.vue
components/PatientOverview.vue
components/PatientOverviewGraph.vue
nuxt.config.js
package.json
pages/patient.vue
plugins/vue-apexchart.ts
yarn.lock

作業内容
- Apexchartsの導入
- 各種コンポーネントの作成
- デザイン調整

WIP: グラフ部分のコンポーネントの作成

---

components/PatientOverviewGraph.vue

- 患者データ一覧のグラフ部分のtooltipを有効化しました(#8 関連)

患者データ一覧のグラフ部分のtooltipを有効にした

---

components/SortSelect.vue

- 患者一覧のソート機能の選択肢を追加しました
- slugとかもこれで良いのか?! など思っており、自信がないため ご確認及びアドバイスいただけると幸いです
(#8)

Add sort selections

---

components/PatientOverview.vue
pages/index.vue

体温・脈拍を最終更新カラムに移動した

---

assets/variables.scss
components/InputField.vue
components/ModalBase.vue
components/PatientRegister.vue

直下にブランチ作成してしまい申し訳ありません。
お手数おかけしますがよろしくお願いいたします。

新規患者登録モーダルのレイアウトとスタイル調整完了しました

---

assets/variables.scss
components/ModalBase.vue
components/PatientRegister.vue
components/PatientRegistered.vue

登録完了モーダルのレイアウトとスタイル修正完了しました。

---

.github/renovate.json
renovate.json

renovate.jsonを編集

---

.github/workflows/reviewdog.yml

reviewdog.ymlを追加

---

.eslintrc.js
nuxt.config.js
package.json
pages/login.vue
services/AuthService.ts
store/index.ts
store/modules/auth.ts
types/auth.d.ts
utils/store-accessor.ts
yarn.lock

closes #121 ログイン機能を実装した。
/login からログインをを行ったら、'/' に移動する。

#121 login 機能を実装する

---

services/AuthService.ts

fix import error

---

assets/global.scss
assets/variables.scss
components/HiddenSelect.vue
components/PageHeader.vue
components/PatientOverview.vue
components/PatientOverviewGraph.vue
components/SearchField.vue
components/SortSelect.vue
pages/index.vue

患者一覧のレイアウトとスタイル調整完了しました。

---

components/PatientOverview.vue

statusesがapiのデフォルトで降順（新しい順）になっていたので修正しました。

lastStatusの取得を修正

---

components/ActionButton.vue
components/InputField.vue
components/PatientOverview.vue
components/PatientRegister.vue
components/PatientRegistered.vue
components/SymptomsStatus.vue
pages/index.vue
pages/login.vue
store/modules/patients.ts
types/component-interfaces/patient.d.ts

#145 
懸案事項
- 患者IDは保健師側で決める必要がありそう？（patientIdを空でpostできない）
- SMSショートメッセージが送られない
- SMSショートメッセージ再送はどうやってやればいいのか
- 新規患者登録後の一覧のソートをどうするか（今だと追加直後に一番最後に配置される）

新規患者登録機能を実装

---

components/PatientOverview.vue
components/PatientOverviewGraph.vue
pages/index.vue

患者一覧のスタイルを調整

---

components/PatientOverview.vue
components/PatientOverviewGraph.vue

患者一覧のグラフとデータの紐付けをした

---

components/Sidebar.vue
pages/centers/_centerId.vue
pages/index.vue
pages/login.vue
services/NurseService.ts
services/PatientService.ts
store/modules/nurses.ts
store/modules/patients.ts
types/component-interfaces/nurse.d.ts
types/component-interfaces/patient.d.ts
utils/store-accessor.ts

#130 
SSIA
- 一つの保健所にしか所属してない保健師は、ログイン後直接患者一覧画面へ
- ルーティングはもうちょっと考えた方がいいかもしれない
TODO: 
- 保健所選択セレクトボックスの表示をcenterNameにする
保健所選択画面は暫定的にこのようにしました↓

保健所選択機能を実装

---

components/Sidebar.vue
pages/index.vue
pages/login.vue

close #130 
index.vueにおいてあったセレクトボックスは削除しました。

保健所選択セレクトボックスを保健所名に

---

components/PatientGraph.vue
pages/patient/_patientId.vue

- 患者詳細頁の図及び患者状態のデータの紐付けを行った
#8

患者詳細頁のグラフとデータの紐付けをした

---

components/SortSelect.vue
pages/center/_centerId.vue

開始日ソート（policy_acceptedの日付ソート）を実装

---

.env.example
nuxt.config.js
services/AuthService.ts
services/NurseService.ts
services/PatientService.ts
services/UserService.ts

API_URLをenvから取得するように修正

---

components/PatientGraph.vue
components/PatientOverviewGraph.vue

グラフの線をストレートに・患者詳細画面ではX軸に時刻を追加

---

pages/center/_centerId/index.vue
services/AuthService.ts
store/modules/auth.ts
types/auth.d.ts

患者一覧画面のsetIntervalでfetchするところに有効期限切れの判定を入れました。

tokenが有効期限切れの時にrefreshTokenでloginをたたくように修正

---

components/ActionButton.vue
components/PatientRegister.vue
pages/center/_centerId/index.vue

close #195 
- 電話番号のハイフンをトリム
- 11桁チェック
- PromiseでisProcessingを有効に -> spinnerを表示

電話番号のバリデーションを追加

---

components/PatientOverview.vue

SpO2、体温、脈拍で閾値を設定

---

components/SortSelect.vue
pages/center/_centerId/index.vue
store/modules/utils.ts
utils/store-accessor.ts

close #202 
SpO2が低い順を追加したことにともない、ソートのメソッドを整理しました。

患者一覧画面にSpO2の低い順のソート機能を追加

---

components/SortSelect.vue
pages/center/_centerId/index.vue
store/modules/utils.ts

ソート項目に体温が高い順を追加

---

nuxt.config.js

routerのmodeをhashに設定

---

components/PatientGraph.vue
components/PatientOverviewGraph.vue

SpO2グラフのminを80に修正

---

components/PatientRegister.vue

電話番号フィールドのlabelを修正、placeholderを削除

---

components/PatientRegister.vue
components/PatientRegistered.vue
components/VCheckbox.vue
pages/center/_centerId/index.vue
types/component-interfaces/patient.d.ts

患者登録時にSMS送信可否のチェックをするように修正

---

.env.example
nuxt.config.js

本番運用するときは、`.env` を作成し、 `.env.example` の内容を本番用に書き換えて配置してください。

apiのurlを変更

---

buildspec.yml

ステージング環境構築に伴う対応

---

components/PatientRegistered.vue
nuxt.config.js
package.json
plugins/axios.ts
services/AuthService.ts
services/NurseService.ts
services/PatientService.ts
services/UserService.ts
tsconfig.json
utils/api-accessor.ts
yarn.lock

axiosを@nuxtjs/axiosに移行、runtimeConfigを設定

---

components/Sidebar.vue
pages/center/_centerId/index.vue
pages/login.vue
services/AuthService.ts
services/auth-header.ts
store/modules/auth.ts
types/auth.d.ts

fix #247 fix login process

---

LICENSE
README.md

close  #320 ライセンスを GNU AGPL v3 に変更する

---

package.json
yarn.lock

vueアップデート＆yarn.lockリフレッシュ（Vue packages version mismatchのため）

---

components/Sidebar.vue
pages/center/index.vue

サイドバーの「保健所を選択」セレクトボックスの不具合を修正

---

components/SearchField.vue
pages/center/_centerId/index.vue

close #413 
- memoとphoneを部分一致で検索します。
- 検索ワードが入っている時はintervalを止めるようにしました。
- 検索ワードは空の時はintervalを走らせるようにしました。

患者一覧の検索機能を追加

---

components/ActionButton.vue
components/CheckboxField.vue
components/InputField.vue
components/InputNumberField.vue
components/ModalBase.vue
components/SymptomsHistory.vue
components/VInputField.vue
nuxt.config.js
package.json
pages/center/_centerId/patient/_patientId.vue
plugins/vee-validate.ts
services/UserService.ts
static/icon-delete.svg
store/modules/statuses.ts
types/component-interfaces/status.d.ts
yarn.lock

close #405 
- 患者詳細画面に「体調を記録」UIを追加しました
- 患者詳細画面の症状テーブルの右に削除機能を追加しました

患者代行入力UIを追加

---

components/Sidebar.vue

現在helpページは存在しないので、一旦リンクを削除します。

helpページへのリンクを削除

---

components/SymptomsHistory.vue

患者詳細画面で症状が削除できない不具合を修正

---

components/PatientRegister.vue
pages/center/_centerId/index.vue
types/component-interfaces/patient.d.ts

close #427 
SSIA
チェックボックスはデフォルトでtrueとします。

新規患者登録モーダルに利用規約同意をスキップするチェックボックスを追加

---

pages/center/_centerId/patient/_patientId.vue

SSIA
さかのぼって入力した際に、順番がおかしくなる不具合を修正しました。

症状入力の日時をUTCでPOSTするように修正

---

package.json
yarn.lock

ステージングリリース

---

components/CheckboxField.vue
components/ModalBase.vue
components/PatientOverview.vue
components/PatientOverviewGraph.vue
components/SymptomsHistory.vue
pages/center/_centerId/patient/_patientId.vue
types/component-interfaces/status.d.ts

患者一覧↓
患者詳細（下部）↓
体調記録フォーム↓
ダウンロードcsv↓

症状報告の項目を追加（「全身倦怠感」「嘔気・嘔吐」「下痢」「食事困難」「半日排尿がない」）
